name: build:afs-leftbin-play-uc1:main
on:
  push:
    branches:
      - main

jobs:
  build-code:
    runs-on: ubuntu-latest
    name: go build
    steps:
      - uses: actions/checkout@v3
      - uses: plantoncloud/gh-action-build-golang@main
        with:
          planton_cloud_service_cli_env: live
          planton_cloud_service_client_id: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_ID }}
          planton_cloud_service_client_secret: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_SECRET }}
          planton_cloud_artifact_store_id: afs-leftbin-play-uc1
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-directory
          path: build/
          if-no-files-found: error

  build-image:
    runs-on: ubuntu-latest
    needs: build-code
    name: docker build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-directory
          path: build/
      - uses: plantoncloud/gh-action-build-docker@main
        with:
          planton_cloud_service_cli_env: live
          planton_cloud_service_client_id: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_ID }}
          planton_cloud_service_client_secret: ${{ secrets.PLANTON_CLOUD_SERVICE_CLIENT_SECRET }}
          planton_cloud_artifact_store_id: afs-leftbin-play-uc1
          planton_cloud_artifact_store_docker_repo_hostname: us-central1-docker.pkg.dev
          container_image_name: us-central1-docker.pkg.dev/planton-shared-services-lo/afs-leftbin-play-uc1-docker/github.com/leftbin-playground/todo-api-golang
          container_image_version: ${{ github.sha }}
